pathInfo:
  baseDir: &baseDir /home/mchrnwsk/qmmm/runs/expanding_reaction_scope/quinoline/optimise/lmf
  orcaPath: &orca /home/mchrnwsk/orca_6_0_1_linux_x86-64_shared_openmpi416/orca
  pythonPath: &python /home/mchrnwsk/.conda/envs/qm/bin/python
  scriptsPath: &scripts /home/mchrnwsk/qmmm/scripts
  forceFields:
    forceFieldPathMD: &forceFieldPathMD ""
  inputStructurePath: &inputStructurePath /home/mchrnwsk/qmmm/runs/expanding_reaction_scope/quinoline/optimise/lmf/lmf.xyz

workflow:
  - stepName: LMF_opt_unrest
    task:
      type: *orca
      orcaInputInfo:
        title: QM Unrestrained Optimization for LMF
        inputFile: *inputStructurePath
        moleculeInfo:
          charge: -1
          multiplicity: 3
        qmMethod: XTB2
        parallelize: 8
        maxcore: 2500