pathInfo:
  baseDir: &baseDir /home/mchrnwsk/qmmm/runs/expanding_reaction_scope/ellipticine/optimise/sub+H2.
  orcaPath: &orca /home/mchrnwsk/orca_6_0_1_linux_x86-64_shared_openmpi416/orca
  pythonPath: &python /home/mchrnwsk/.conda/envs/qm/bin/python
  scriptsPath: &scripts /home/mchrnwsk/qmmm/scripts
  forceFields:
    forceFieldPathMD: &forceFieldPathMD ""
  inputStructurePath: &inputStructurePath /home/mchrnwsk/qmmm/runs/expanding_reaction_scope/ellipticine/optimise/sub+H2./sub+H2.xyz

workflow:
  - stepName: SUB_opt_unrest
    task:
      type: *orca
      orcaInputInfo:
        title: QM Unrestrained Optimization for singly-oxidised 4,7-dimethyl-5-anilinoquinoline
        inputFile: *inputStructurePath
        moleculeInfo:
          charge: 1
          multiplicity: 3
        qmMethod: XTB2
        parallelize: 8
        maxcore: 2500